name: Create Files in New Repository

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Prompt user for input
        run: |
          echo "::workflow-command::{\"command\":\"user-input\",\"inputs\":[{\"id\":\"name\",\"description\":\"Enter your name\"}]}"
          USER_INPUT=${{ env.user_input_name }}
          echo "Hello $USER_INPUT!"
          
  process_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        with:
          token: ${{ secrets.PAT_TOKEN }}
        uses: actions/checkout@v3

      - name: Set API Response as Environment Variable
        run: |
          echo "api_response='<answer> package.json, README.md, .gitignore, yarn.lock, babel.config.js, src/index.js, src/server.js, src/routes.js, src/app.js, src/weather.js, .eslintrc.json, .gitattributes, .editorconfig, test/test-helper.js, test/weather.test.js, public/index.html, public/favicon.ico, public/index.css, public/assets/css/weather.css, public/assets/css/bootstrap.css, public/assets/img/rainy.png, public/assets/img/cloud.png, public/assets/img/sunny.png, public/assets/img/windy.png</answer>'" >> $GITHUB_ENV

      - name: Create and Push Files
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Create files
        run: |
          files=$(echo "$api_response" | sed -n 's/.*<answer>\(.*\)<\/answer>.*/\1/p' | tr -d ' ' | tr ',' '\n')
          for file in $files; do
            if [[ $file == *"/"* ]]; then
              dir=$(dirname "$file")
              mkdir -p "$dir"
            fi
            echo "Creating file: $file"
            echo "Content for $file" > "$file"
          done

      - name: Initialize Git and add files
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
      - name: Commit and push changes
        continue-on-error: true
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Automated file creation"
          git push
