name: API Automation

on:
  push:
    branches:
      - main

jobs:
  process_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read data from file
        run: |
          data=$(cat README.md)
          echo "Data from file: $data"

      - name: Call API
        id: api_call
        run: |
          echo "api_response='<answer> package.json, README.md, .gitignore, yarn.lock, babel.config.js, src/index.js, src/server.js, src/routes.js, src/app.js, src/weather.js, .eslintrc.json, .gitattributes, .editorconfig, test/test-helper.js, test/weather.test.js, public/index.html, public/favicon.ico, public/index.css, public/assets/css/weather.css, public/assets/css/bootstrap.css, public/assets/img/rainy.png, public/assets/img/cloud.png, public/assets/img/sunny.png, public/assets/img/windy.png</answer>'" >> $GITHUB_ENV

      - name: Create Files
        run: |
          # Extract file names from api_response
          files=$(echo "$api_response" | sed -n 's/.*<answer>\(.*\)<\/answer>.*/\1/p')
          
          # Loop through each file name and create files
          for file in $files; do
            # Check if the file name includes directories
            if [[ $file == *"/"* ]]; then
              # Extract directory name
              dir=$(dirname "$file")
              # Create directory if it doesn't exist
              mkdir -p "$dir"
            fi
            echo "Creating file: $file"
            echo "Content for $file" > "$file"
          done

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add files based on API response"
          # Use the PAT for authentication
          git push https://github.com/${{ github.repository }}.git HEAD:main
