name: Create Files in New Repository

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  process_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set API Response as Environment Variable
        run: |
          echo "api_response='<answer> package.json, README.md, .gitignore, yarn.lock, babel.config.js, src/index.js, src/server.js, src/routes.js, src/app.js, src/weather.js, .eslintrc.json, .gitattributes, .editorconfig, test/test-helper.js, test/weather.test.js, public/index.html, public/favicon.ico, public/index.css, public/assets/css/weather.css, public/assets/css/bootstrap.css, public/assets/img/rainy.png, public/assets/img/cloud.png, public/assets/img/sunny.png, public/assets/img/windy.png</answer>'" >> $GITHUB_ENV

      - name: Create and Push Files
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Create files
        run: |
          files=$(echo "$api_response" | sed -n 's/.*<answer>\(.*\)<\/answer>.*/\1/p' | tr -d ' ' | tr ',' '\n')
          for file in $files; do
            if [[ $file == *"/"* ]]; then
              dir=$(dirname "$file")
              mkdir -p "$dir"
            fi
            echo "Creating file: $file"
            echo "Content for $file" > "$file"
          done

      - name: Initialize Git and add files
        run: |
          git init
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Initial commit"
          git branch -M main
          # Replace <REPO_NAME> with your new repository name
          # Replace <YOUR_USERNAME> with your GitHub username
          git remote add origin https://github.com/likhithnemani/sample.git
          git push -u origin main
