name: API Call with User Interaction

on:
  # Replace with your desired trigger event (e.g., push, schedule)
  push:
    branches: [ main ]

jobs:
  with-interaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (if needed)
        # Replace with any required installation commands
        run: npm install axios

      - name: Make API call
        uses: mashape/github-action-http-request@v1.4.1
        with:
          url: https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2  # Replace with your API endpoint
          method: POST  # Replace with appropriate method (GET, POST, etc.)
          headers: "Authorization: Bearer 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" # Adjust headers if needed
          json: "{'input': 'sample'}"
          # Add authentication details if required

      - name: Parse API response
        run: |
          response_data=$(echo ${{ steps.make_api_call.outputs.body }})
          # Extract relevant information from response_data
          extracted_data=$(echo $response_data | jq -r '.message')  # Replace with your parsing logic

      - name: Display response and buttons
        run: |
          echo "API Response: $extracted_data"
          echo ""
          echo "Please choose an option:"
          echo "1. Continue workflow"
          echo "2. Cancel workflow"
          read -r user_choice

      - name: Branch workflow based on user choice
        uses: actions/checkout@v3  # Checkout code again (optional)
        with:
          persist-credentials: true
        run: |
          if [[ $user_choice -eq 1 ]]; then
            # Continue workflow steps
            echo "Continuing workflow..."
            # Add your steps to continue the workflow
          else
            echo "Workflow cancelled."
            # Optionally perform any cleanup steps here
          fi
