name: API Automation

on:
  push:
    branches:
      - main

jobs:
  process_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read data from file
        run: |
          data=$(cat README.md)
          echo "Data from file: $data"
