name: Workflow with Interactive Steps

on:
  push:
    branches:
      - main

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python validate.py
        id: python-script

      - name: Send message with buttons
        if: always()
        run: |
          echo "::warning::Please click [Continue](#continue) to proceed or [Cancel](#cancel) to cancel."
          echo "::error::User input required."

  continue_or_cancel:
    needs: run_python_script
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'action_required'

    steps:
      - name: Check user input
        if: github.event.workflow_run.conclusion == 'success'
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
            echo "User clicked Continue."
            # Continue with workflow steps
          else
            echo "User clicked Cancel."
            # Stop the workflow or take appropriate action
          fi
